"""casacade

Revision ID: 20dab1348d4b
Revises: 57f246c97ff9
Create Date: 2024-10-10 17:15:50.854614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dab1348d4b'
down_revision = '57f246c97ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizza_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('pizza_ingredient_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'menu', ['menu_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizza_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pizza_ingredient_ibfk_2', 'menu', ['menu_id'], ['id'])

    # ### end Alembic commands ###
