"""Initial migration.

Revision ID: 2a2d2ba79938
Revises: 97b5d178a6c5
Create Date: 2024-10-06 12:34:49.299160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a2d2ba79938'
down_revision = '97b5d178a6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_personal_information', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_personal_information', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
