"""added admin bool

Revision ID: 9359b8d44c07
Revises: 
Create Date: 2024-10-10 13:52:17.979177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9359b8d44c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('customer_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_personal_information', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=30), nullable=True))

    # ### end Alembic commands ###
