"""initial migration

Revision ID: 97b5d178a6c5
Revises: 
Create Date: 2024-10-06 12:09:34.423011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b5d178a6c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_personal_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=18), nullable=True),
    sa.Column('previous_orders', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_area', sa.String(length=50), nullable=True),
    sa.Column('last_delivery', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=True),
    sa.Column('is_vegan', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('delivery_eta', sa.DateTime(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_personal_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pizza_ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivered_by', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('pizza_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivered_by'], ['delivery_driver.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordered_pizza_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_order_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['sub_order_id'], ['sub_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordered_pizza_ingredients')
    op.drop_table('sub_order')
    op.drop_table('delivery')
    op.drop_table('pizza_ingredient')
    op.drop_table('customer_orders')
    op.drop_table('menu')
    op.drop_table('ingredient')
    op.drop_table('discounts')
    op.drop_table('delivery_driver')
    op.drop_table('customer_personal_information')
    # ### end Alembic commands ###
