"""adress

Revision ID: e296fabcccf4
Revises: af1bd2fd958a
Create Date: 2024-10-11 12:03:29.450502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e296fabcccf4'
down_revision = 'af1bd2fd958a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('customer_personal_information', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_personal_information', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
