"""initial

Revision ID: edf1b0c252a9
Revises: 
Create Date: 2024-10-14 18:20:59.312226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf1b0c252a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_order', sa.DateTime(), nullable=True))

    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('customer_personal_information', schema=None) as batch_op:
        batch_op.drop_column('last_order')

    # ### end Alembic commands ###
